# Figure 5

```{r imports}
#| cache: false
#| message: false
library(dplyr)
library(stringr)    # str_remove
library(purrr)      # map_df
library(readr)      # read_csv
library(tidyr)      # pivot_wider
library(ggalign)    # ggheatmap
library(forcats)    # fct, fct_reorder

source("R/config.R")
```

```{r figure-05-clust-pred-features}
#| cache: true
#| fig.width: 10
#| fig.height: 3.6
files_rank <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            "05-r-varsel-output") %>%
  dir("^rank_week[0-9]{1,2}[.]csv",
      full.names = TRUE) %>%
  ## Sort file names numerically.
  .[order(as.numeric(str_extract(., "rank_week(.+)[.]csv", group = 1)))]
files_size <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            "05-r-varsel-output") %>%
  dir("^size_week[0-9]{1,2}[.]txt",
      full.names = TRUE) %>%
  ## Sort file names numerically.
  .[order(as.numeric(str_extract(., "size_week(.+)[.]txt", group = 1)))]

## Read in the ordered predictive variables.
df_ord <-
  files_rank %>%
  map_df(read_csv, show_col_types = FALSE,
         .id = "week") %>%
  mutate(across(week:size, as.integer))
df_ord

## Read in the calculated sufficient number of predictive variables.
suppressWarnings({
  ## Ignore the warning from converting the NA character to an NA integer.
  n_suff <-
    files_size %>%
    map_chr(read_lines) %>%
    as.integer()
})
n_suff

## Compare how much different the sufficient number is from the full list.
n_vars <-
  df_ord %>%
  filter(ranking_fulldata != "(Intercept)") %>%
  count(week) %>%
  mutate(n_suff = n_suff,
         diff = ifelse(is.na(n_suff),
                       0L, n - n_suff),
         n_vars = n - diff) %>%
  print(n = Inf)

## Frequency of features (with Bayesian variable selection).
df_varsel <-
  df_ord %>%
  filter(ranking_fulldata != "(Intercept)") %>%
  inner_join(select(n_vars, week, n_vars), by = "week") %>%
  filter(row_number() <= n_vars, .by = week) %>%
  select(-n_vars)
df_varsel

## Descriptive feature names.
names_map <- c(
  "gran_AreaShape_MajorAxisLength_mean" =
    "Granuloma major-axis length",
  "gran_Intensity_StdIntensity_tnf_mean" =
    "TNF standard deviation in granuloma",
  "mac_Intensity_IntegratedIntensityEdge_ifng_mean" =
    "Macrophage activation signal",
  "mac_Intensity_IntegratedIntensityEdge_tnf_mean" =
    "TNF (edge) proximal to macrophages",
  "mac_Neighbors_AngleBetweenNeighbors_60_mean" =
    "Angle between neighboring macrophages",
  "mac_Neighbors_NumberOfNeighbors_60_IQR" =
    "Macrophage number of neighbors",
  "mac_Neighbors_SecondClosestDistance_60_mean" =
    "Distance (mean) from macrophage to second-closest cell",
  "t_gam_Neighbors_SecondClosestDistance_60_median" =
    "Distance (median) from T cells activating macrophages to second-closest cell",
  "gran_RadialDistribution_RadialCV_tnf_1of4_mean" =
    "Inner granuloma macrophage activation signal",
  ## https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.moments_central
  "macs_AreaShape_CentralMoment_0_2_mean" =
    "Macrophage aggregate y variance",
  "macs_AreaShape_CentralMoment_2_0_mean" =
    "Macrophage aggregate x variance",
  "macs_AreaShape_MeanRadius_mean" =
    "Macrophage aggregate radius",
  "macs_AreaShape_Perimeter_mean" =
    "Macrophage aggregate perimeter",
  "macs_RadialDistribution_RadialCV_tnf_2of4_mean" =
    "Inner-middle granuloma macrophage activation signal variance",
  "macs_RadialDistribution_RadialCV_tnf_3of4_mean" =
    "Outer-middle granuloma macrophage activation signal variance",
  "macs_Intensity_MaxIntensity_tnf_mean" =
    "TNF (maximum) proximal to macrophages",
  "gran_Intensity_MeanIntensity_tnf_mean" =
    "TNF in granuloma",
  "mac_Children_macs_Count_mean" =
    "1 / (Number of macrophages)",
  "mac_Neighbors_SecondClosestDistance_60_median" =
    "Distance (median) from macrophage to second-closest cell",
  "mac_Neighbors_NumberOfNeighbors_60_mean" =
    "Macrophage mean number of neighbors",
  "mac_Neighbors_NumberOfNeighbors_60_median" =
    "Macrophage median number of neighbors",
  "gran_AreaShape_MedianRadius_mean" =
    "Granuloma median radius",
  "macs_RadialDistribution_FracAtD_ifng_1of4_mean" =
    "Inner granuloma macrophage activation signal",
  "macs_RadialDistribution_FracAtD_ifng_4of4_mean" =
    "Outer granuloma macrophage activation signal",
  "macs_RadialDistribution_FracAtD_tnf_4of4_mean" =
    "Outer granuloma TNF",
  "t_cyts_AreaShape_EquivalentDiameter_mean" =
    "Cytotoxic T cell aggregate diameter",
  "t_cyts_Intensity_UpperQuartileIntensity_tnf_mean" =
    "TNF proximal to cytotoxic T cells",
  "t_gam_Location_CenterMassIntensity_X_tnf_IQR" =
    "T cells activating macrophages x-distribution",
  "t_gam_Location_CenterMassIntensity_Y_tnf_IQR" =
    "T cells activating macrophages y-distribution",
  "t_gam_Intensity_IntegratedIntensityEdge_tnf_mean" =
    "TNF proximal to T cells activating macrophages",
  "ts_Intensity_StdIntensity_tnf_mean" =
    "TNF proximal to T cells",
  "macs_Intensity_StdIntensity_tnf_mean" =
    "TNF variation proximal to macrophages",
  "t_gam_AreaShape_BoundingBoxMaximum_X_IQR" =
    "T cells activating macrophages x-edges",
  "t_gam_AreaShape_BoundingBoxMaximum_Y_IQR" =
    "T cells activating macrophages y-edges",
  "t_regs_AreaShape_EquivalentDiameter_mean" =
    "Regulatory T cell aggregate diameter",
  "macs_RadialDistribution_FracAtD_ifng_3of4_mean" =
    "Mid granuloma macrophage activation signal",
  "mac_Location_CenterMassIntensity_Y_ifng_IQR" =
    "Macrophage activation signal distribution along y-axis",
  "mac_Location_CenterMassIntensity_X_ifng_IQR" =
    "Macrophage activation signal distribution along x-axis",
  "ts_Intensity_StdIntensityEdge_tnf_mean" =
    "TNF standard deviation at granuloma edge",
  "mac_Neighbors_FirstClosestDistance_t_reg_60_median" =
    "Distance from macrophage to closest regulatory T cell",
  "ts_AreaShape_EquivalentDiameter_mean" =
    "All T cells aggregate equivalent diameter",
  ## https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_euler_number.html
  "ts_AreaShape_EulerNumber_mean" =
    "All T cells aggregate lymphcytic cuff",
  "ts_AreaShape_FormFactor_mean" =
    "All T cells aggregate circularity",
  "ts_AreaShape_MeanRadius_mean" =
    "All T cells aggregate mean radius",
  "t_gam_Children_t_gams_Count_mean" =
    "1 / (Number of T cells activating macrophages)",
  "t_gams_AreaShape_MajorAxisLength_mean" =
    "T cells activating macrophages aggregate major-axis length",
  "t_gams_AreaShape_MinorAxisLength_mean" =
    "T cells activating macrophages aggregate minor-axis length"
)
## Plot clustered heatmap.
mat_full <-
  df_varsel %>%
  ## Remove features that appear for fewer than 3 contiguous weeks.
  inner_join(df_varsel %>%
               pivot_wider(
                 id_cols = ranking_fulldata,
                 names_from = week,
                 values_from = size,
                 values_fill = 0L) %>%
               nest(n = -ranking_fulldata) %>%
               rowwise() %>%
               mutate(n = (function(x) {
                 rle <-
                   unlist(x) |>
                   (function(x) x > 0L)() |>
                   rle()
                 max(rle$lengths[rle$values])
               })(n)) %>%
               filter(n >= 4) %>%
               select(-n),
             by = "ranking_fulldata") %>%
  pivot_wider(id_cols = ranking_fulldata,
              names_from = week,
              values_from = size) %>%
  tibble::column_to_rownames(var = "ranking_fulldata") %>%
  as.matrix()
rownames(mat_full) <-
  names_map[rownames(mat_full)] %>%
  setNames(NULL)
## NA values will cause hclust to fail.
d_mat <- max(mat_full, na.rm = TRUE) + 1L - mat_full
d_mat[is.na(d_mat)] <- Inf
d <- dist(d_mat, method = "canberra")
n_clusters <- 3L
colors_cluster <-
  palette.colors(4, palette = "Okabe-Ito")[-1] %>%
  setNames(c("Transient", "Formation", "Maintenance"))
labels_cluster <-
    c("Maintenance",
      "Formation",
      "Transient",
      "Maintenance") %>%
  factor(levels = c("Formation", "Transient", "Maintenance"))
ggheatmap(mat_full, filling = NULL) +
  ## Outline tiles with black lines and leave small gaps to distinguish
  ## contiguous dark tiles.
  geom_tile(aes(fill = value), color = "black", width = 0.95, height = 0.95) +
  scale_y_continuous(position = "right") +
  labs(x = "Week",
       y = "Spatial feature",
       fill = "Rank") +
  ## Color-bind friendly palette.
  scale_fill_gradient(low = "black",
                      high = "gray90",
                      na.value = "white",
                      breaks = c(1, 18),
                      labels = c("More\npredictive", "Less\npredictive"),
                      guide = guide_colorbar(reverse = TRUE)) +
  theme(legend.position = "left",
        legend.text = element_text(vjust = 1)) +
  anno_left(size = unit(5, "char")) +
  align_dendro(k = n_clusters,
               distance = d,
               aes(color = labels_cluster[branch])) +
  scale_color_manual(values = colors_cluster) +
  geom_point() +
  ## Remove unnecessary labels of align_dendro().
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "left") +
  labs(x = NULL,
       color = "Cluster") +
  guides(color = guide_legend())
```
	
```{r session-info}
#| cache: false
sessionInfo()
```
