# Figure 9

```{r imports}
#| cache: false
#| message: false
library(dplyr)
library(hdf5r)
library(tidyr)
library(stringr)
library(forcats)
library(purrr)
library(Matrix)  # spMatrix
library(Rglpk)   # Rglpk_solve_LP
library(ggrepel) # geom_text_repel
library(readr)

source("R/config.R")
```

```{r figure-prcc}
#| cache: true
#| fig.width: 5.2
#| fig.height: 7
files_type <- c("consensus", "indeterminate")
files_prcc <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            str_c("06-prcc_ot_", files_type, "_9.mat"))
read_prcc <- function(path) {
  ## Run PRCC for all outcomes.
  h5 <- H5File$new(path, mode = "r")
  prcc_result <- h5[["prccResult"]]
  x <- as.integer(prcc_result[["analysisTimePoints"]]$read() / ticks_per_day)
  read_cellarray_as_characters <- function(member)
    ## Cell Arrays are H5R objects that need to be dereferenced.
    lapply(prcc_result[[member]]$read()$dereference(),
           function(x) intToUtf8(x$read())) %>%
      unlist()
  output_names <-
    read_cellarray_as_characters("modelOutputNames")
  param_names <-
    read_cellarray_as_characters("paramNames")
  ## Dimensions = [timepoints, outputs, parameters]
  prcc <- prcc_result[["uncorrectedPrcc"]]$read()
  ## Note that significance-corrected PRCV values in the HDF5 file simply
  ## replace insiginificant values, defined as those values that exceed a
  ## threshold, alpha, with NAs.  Therefore, instead read the more informative
  ## PRCC p-values before they are NA replaced.
  signif_uncorr <- prcc_result[["uncorrectedSignificance"]]$read()
  signif_bh <- prcc_result[["bhfdrSignificance"]]$read()
  h5$close_all()
  enframe_matrix <- function(mat, name) {
    ## Coercing the array to a tibble causes the first dimension to become the
    ## rows, and the product of the second and third dimensions to become the
    ## columns.
    as_tibble(mat) %>%
    `colnames<-`(paste(rep(output_names, times = n_params),
                       rep(param_names, each = n_outputs),
                       sep = "|")) %>%
      mutate(day = x, .before = 1L) %>%
      gather(key = "output_param", value = "value", -day, convert = FALSE) %>%
      ## Separate takes the longest time to run.
      separate(output_param, into = c("output", "param"), sep = "[|]") %>%
      mutate(value = ifelse(value == 1L, NA, value)) %>%
      rename(all_of(setNames(c("value"), name)))
  }
  enframe_matrices <- function(lists) {
    stopifnot(is.list(lists))
    stopifnot(! is.null(names(lists)))
    dfs <- map2(lists, names(lists), enframe_matrix)
    if (length(dfs) > 1) {
      dfs <-
        c(dfs[[1]],
          dfs[-1] |>
            map(~ select(.x, last_col())))
    }
    bind_cols(dfs)
  }
  n_outputs <- length(output_names)
  n_params <- length(param_names)
  enframe_matrices(list(prcc = prcc,
                        signif_uncorr = signif_uncorr,
                        signif_bh = signif_bh))
}
df_prcc_h5 <-
  map(files_prcc, read_prcc) |>
  setNames(files_type) |>
  list_rbind(names_to = "type")
df_prcc <-
  df_prcc_h5 %>%
  mutate(across(starts_with("signif"), ~ pmin(.x, 1))) %>%
  ## Remove parameter prefix.
  mutate(param = str_remove(param, "GR[.]")) %>%
  ## Remove uninteresting parameters.
  filter(! str_detect(param,
                      str_c(c("@initDensity$",
                              "movement",
                              "@time",
                              "HalfSat",
                              "nrIntMtb",
                              "threshold",
                              "@estConsRate",
                              "@kApoptosis$"),
                            collapse = "|"))) %>%
  ## Rename parameters to be more legible.
  mutate(
    param_orig = param,
    param =
      ## Rename parameters to be more legible.
      fct(param) %>%
      fct_recode(
        "IL10 from activated macrophages" =
            "Core.Mac/@dIL10Act",
        "IL10 from infected macrophages" =
            "Core.Mac/@dIL10Inf",
        "Macrophage recruitment" =
          "Recruit.Prob.Mac/@maxRecProb",
        "Regulatory T cell recruitment" =
          "Recruit.Prob.Tcell.Treg/@maxRecProb",
        "IFN-γ+ T cell recruitment" =
          "Recruit.Prob.Tcell.Tgam/@maxRecProb",
        "CTL recruitment" =
          "Recruit.Prob.Tcell.Tcyt/@maxRecProb",
        "% Mtb-specific CTL" =
          "Recruit.Prob.Tcell.Tcyt/@probCognate",
        "% Mtb-specific IFN-γ+ T cell" =
          "Recruit.Prob.Tcell.Tgam/@probCognate",
        "TNF from IFN-γ+ T cells" =
          "Core.Tcell.Tgam/@probTNFProducer",
        "TNF from CTLs" =
          "Core.Tcell.Tcyt/@probTNFProducer",
        "IL10 diffusivity" =
          "Core/@diffusivityIL10",
        "Caseation from cell death" =
          "Core/@nrKillingsCaseation")) %>%
  ## Convert days to weeks.
  mutate(week = as.integer(day / 7L), .before = day) %>%
  select(-day) %>%
  ## Tweak output labels.
  mutate(
    type = str_to_sentence(type),
    output =
      ## Set order of outputs.
      fct_inorder(output) %>%
      fct_relevel("MaxGranulomaDiameter",
                  "CaseumRatio",
                  "TotMtbInGranScaledRing",
                  after = 0) %>%
      ## Rename outputs.
      fct_recode(
        "Granuloma diameter" = "MaxGranulomaDiameter",
        "Caseum-granuloma ratio" = "CaseumRatio",
        "Macrophages" = "Mac ScaledRing",
        "IFN-γ+ T cells" = "Tgam ScaledRing",
        "CTLs" = "Tcyt ScaledRing",
        "Regulatory T cells" = "Treg ScaledRing",
        "CFU" = "TotMtbInGranScaledRing"))
## Note that the significance columns are for individual PRCC values; this
## next test is for the lines.
df_prcc_signif <-
  df_prcc %>%
  drop_na() %>%
  group_by(type, output) %>%
  filter(prcc %in% boxplot.stats(prcc)$out) %>%
  ungroup() %>%
  distinct(type, output, param) %>%
  mutate(week = 22L) %>%
  left_join(df_prcc,
            by = c("type", "week", "output", "param"))
###############################################################################
## Begin block to ensure intersecting parameter lines have different colors.
###############################################################################
params_signif <- pull(distinct(df_prcc_signif, param))
params_signif_int <- as.integer(params_signif)
n_params_signif <- length(params_signif)
n_colors <- length(params_signif)
## Find parameter line intersections:
df_intersect <-
  df_prcc %>%
  mutate(type = as.integer(as.factor(type)),
         output = as.integer(output),
         param = as.integer(param)) %>%
  pivot_wider(id_cols = c(type, week, output),
              names_from = param,
              values_from = prcc) %>%
  group_by(output) %>%
  nest() %>%
  mutate(intersects = map(data, function(df) {
    week <- pull(df, week)
    stopifnot(week == 0:22)
    mat <-
      select(df, -week) %>%
      as.matrix()
    ## Find combination of differences, take sign, and find if the sign changes
    ## at anytime over the 22 weeks.
    ##
    ## Sign of differences:
    c2 <- combn(ncol(mat), 2)
    diff_sign <- sign(mat[, c2[1, ]] - mat[, c2[2, ]])
    mode(diff_sign) <- "integer"
    colnames(diff_sign) <- apply(c2, 2, str_c, collapse = "_")
    rownames(diff_sign) <- week
    ## Does the sign change?
    has_pos <- apply(diff_sign == 1L, 2, any, na.rm = TRUE)
    has_neg <- apply(diff_sign == -1L, 2, any, na.rm = TRUE)
    data.frame(cmp = colnames(diff_sign),
               intersects = has_pos & has_neg)
  })) %>%
  ungroup() %>%
  select(-data) %>%
  unnest(intersects) %>%
  filter(intersects) %>%
  select(-intersects) %>%
  separate_wider_delim(cmp, delim = "_", names = c("param1", "param2")) %>%
  mutate(across(c(param1, param2), as.integer)) %>%
  arrange(output, param1, param2) %>%
  ## Subset parameters in to df_prcc_signif.
  semi_join(df_prcc_signif %>%
              select(output, param) %>%
              mutate(across(c(output, param), as.integer)) %>%
              rename(param1 = param),
            by = c("output", "param1")) %>%
  semi_join(df_prcc_signif %>%
              select(output, param) %>%
              mutate(across(c(output, param), as.integer)) %>%
              rename(param2 = param),
            by = c("output", "param2")) %>%
  ## Encode to parameter indices.
  select(-output) %>%
  distinct() %>%
  mutate(across(param1:param2,
                function(x)
                  map_vec(x, ~ which(params_signif_int %in% .x))))
## Assign colors that maximize the hue of intersecting lines.
##
## First make sure the constraints are satisfiable before optimizing
## color hues.
constraints_intersect <-
  spMatrix(nrow = nrow(df_intersect) * n_colors,
           ncol = n_params_signif * n_colors,
           i = rep(seq_len(nrow(df_intersect) * n_colors), each = 2),
           j =
             df_intersect %>%
             group_by(i = row_number()) %>%
             nest() %>%
             mutate(vec = map(data, function(df) {
               x <- unlist(df)
               ## Offset by number of colors and repeat for each color
               ## of the parameter.
               mat <- seq_len(n_colors) %*% t(c(1, 1))
               mat + t(replicate(n_colors, n_colors * (x - 1L)))
             })) %>%
             ungroup() %>%
             select(vec) %>%
             unnest(vec) %>%
             pull(vec) %>%
             t() %>%
             c(),
           x = rep(1L, 2 * nrow(df_intersect) * n_colors))
constraints_one_color <-
  spMatrix(nrow = n_params_signif,
           ncol = n_params_signif * n_colors,
           i = rep(seq_len(n_colors), each = n_params_signif),
           j = seq_len(n_colors * n_params_signif),
           x = rep(1L, n_params_signif * n_colors))
satisfiable <-
  Rglpk_solve_LP(obj = rep(1L, n_params_signif * n_colors),
                 mat = rbind(constraints_intersect,
                             constraints_one_color),
                 dir = c(rep("<=", nrow(constraints_intersect)),
                         rep("==", nrow(constraints_one_color))),
                 rhs = c(rep(1L, nrow(constraints_intersect)),
                         rep(1L, nrow(constraints_one_color))),
                 types = rep("B", n_params_signif * n_colors))
stopifnot(satisfiable$status == 0)
## View the color assignments.
colors <-
  matrix(as.logical(satisfiable$solution),
         nrow = n_colors,
         dimnames = list(str_c("c", seq_len(n_colors)),
                         params_signif)) %>%
  t() %>%
  apply(1, which)
colors
set_color_id <- function(param) {
  colors[as.character(param)] %>%
    as.character() %>%
    fct()
}
###############################################################################
## End block to ensure intersecting parameter lines have different colors.
###############################################################################
weeks <- 22L
x_max <- 45L
color_palette <-
  ## Remove yellow because is hard to see even for non-colorblind people.
  palette.colors(max(colors) + 2L, palette = "Okabe-Ito")[-c(1, 5)]
for (type_ in pull(distinct(df_prcc, type))) {
  plot_prcc <- df_prcc %>%
  semi_join(df_prcc_signif %>%
              distinct(type, param, output),
            by = c("type", "param", "output")) %>%
  filter(type == type_) %>%
  mutate(color_id = set_color_id(param)) %>%
  ggplot(aes(x = week,
             y = prcc,
             group = param)) +
  facet_wrap(~ output, ncol = 2) +
  theme_bw() +
  theme(
    ## Using clip = "off" in coord_cartesian() together with increasing the
    ## right plot margin allows the geom_text_repel() labels to be outside the
    ## plot area.
    plot.margin = unit(c(0.1, 2.4, 0.1, 0.1), "cm"),
    ## Increase spacing between facet columns.
    panel.spacing.x = unit(4, "lines"),
    ## X-axis title centering looks bad after ajusting panel spacing, so left
    ## align instead.
    axis.title.x = element_text(hjust = 0),
    strip.text = element_text(
      size = 6.6, margin = margin(0.2, 0, 0.2, 0, "lines"))) +
  coord_cartesian(clip = "off") +
  guides(color = "none",
         alpha = "none") +
  labs(x = "Week (post-infection)",
       y = "Partial rank correlation coefficient (PRCC)",
       ## Prevent accidents by including the title and clip out later.
       title = type_) +
  geom_hline(yintercept = 0) +
  geom_line(alpha = 0.1,
            data = anti_join(df_prcc %>%
                               filter(type == type_),
                             distinct(df_prcc_signif, param, output),
                             by = c("param", "output"))) +
  geom_line(aes(color = color_id)) +
  geom_point(data = . %>% filter(type == type_, signif_bh < 0.05),
             aes(color = color_id),
             size = 0.5) +
  geom_text_repel(aes(label = str_wrap(param, width = 20L),
                      color = color_id),
                  lineheight = 0.8,
                  ## Relax y-limit to reduce crowding.
                  ylim = c(-1, 1),
                  ## Constrain labels 1 week after the last timepoint.
                  xlim = c(weeks + 1L, x_max),
                  data = df_prcc_signif %>%
                    filter(type == type_) %>%
                    mutate(color_id = set_color_id(param)),
                  ## Only auto-nudge in y-direction.
                  direction = "y",
                  ## Left align.
                  hjust = 0,
                  ## Draw all segments.
                  min.segment.length = 0,
                  segment.color = "black",
                  segment.curvature = 0,
                  ## Reduce text size.
                  size = 2) +
  geom_point(data = df_prcc_signif %>%
               filter(type == type_),
             size = 1,
             color = "black") +
  scale_color_manual(values = color_palette) +
  ## Remove padding around between data and axes.
  scale_x_continuous(expand = c(0, 0),
                     ## No data at week 0.
                     limits = c(1L, NA)) +
  scale_y_continuous(expand = c(0, 0)) +
  geom_text(aes(x = -Inf,
                y = Inf,
                label = LETTERS[as.integer(output)]),
            hjust = 1.6,
            vjust = -0.5,
            inherit.aes = FALSE)
  print(plot_prcc)
}
```

```{r suppl-figure-param-spatial-corr}
#| cache: true
#| dependson: -1
#| fig.width: 8
#| fig.height: 8

## Plot top correlations of parameters with spatial statistics.
file_stats <-
  file.path(dir_data,
            "2026-02-03-A-gr-20k-3rep",
            "output-lhs-7d-interval-stat-cols-10.csv.zst")
file_features <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            "02-cellprofiler-output-combined",
            "week22.csv.zst")
file_rank <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            "05-r-varsel-output",
            "rank_week22.csv")
## Predictive spatial features.
features <-
  read_csv(
    file_rank,
    col_select = c("size", "ranking_fulldata"),
    col_types = cols(
      size = "i",
      ranking_fulldata = "c")) |>
  filter(size != 0L) |>
  pull(ranking_fulldata)
## PRCC parameters.
df_params_signif <- distinct(df_prcc_signif, param, param_orig)
## The CSV file_features has long lines; the default 2^17 buffer is
## insufficient.
Sys.setenv(VROOM_CONNECTION_SIZE = 2^19)
cols_param <-
  read_csv(zstdfile(file_stats),
           n_max = 0,
           show_col_types = FALSE) |>
  colnames() |>
  str_subset("^GR[.]")
cols_param <-
  cols_param[cols_param %in% str_c("GR.", pull(df_params_signif, param_orig))]
df_param <-
  read_csv(zstdfile(file_stats),
           col_select = c("exp", "time", "TotMtbInGranScaledRing", cols_param),
           col_types = cols(exp = "c", time = "i", .default = "d")) |>
  dplyr::filter(time == max(time)) |>
  select(-time) |>
  dplyr::rename(mtb = TotMtbInGranScaledRing) |>
  ## Experimentally, we do not see granulomas with more than 1M CFU.
  dplyr::filter(! (mtb > 1e6)) |>
  mutate(mtb = log1p(mtb) / log(9)) |>
  ## Cleanup inputs as we did for regression.
  ##
  ## Replace problematic values with zero for now.
  mutate(across(everything(),
                function(x)
                  replace(x, is.na(x) | x < 0 | is.infinite(x), 0))) |>
  ## Remove zero-values.
  filter(mtb > 0) |>
  mutate(rep =
           str_split_i(exp, fixed("."), 2L) |>
           as.integer(),
         exp  =
           as.double(exp) |>
           floor() |>
           as.integer(),
         .after = 1L)  |>
  dplyr::rename(Metadata_Site = exp,
                Metadata_Rep = rep) |>
  inner_join(
    read_csv(
      zstdfile(file_features),
      col_select = c("Metadata_Site", "Metadata_Rep", features),
      col_types =
        cols(Metadata_Site = "i", Metadata_Rep = "i", .default = "d")),
    by = c("Metadata_Site", "Metadata_Rep"))

df_cor_xy <-
  expand_grid(x_name = cols_param,
              y_name = features) |>
  rowwise() |>
  mutate(cor = cor(pull(df_param, x_name),
                   pull(df_param, y_name))) |>
  drop_na() |>
  slice_max(abs(cor), n = 9L) |>
  mutate(x_name = fct_inorder(x_name),
         y_name = fct_inorder(y_name)) |>
  rowwise() |>
  mutate(x = list(pull(df_param, x_name)),
         y = list(pull(df_param, y_name))) |>
  unnest(c(x, y))
df_cor_xy |>
  ggplot(aes(x, y)) +
  theme_bw() +
  theme(strip.text.x = element_text(size = 6.5)) +
  facet_wrap(~ x_name + y_name,
             ncol = 3,
             scales = "free") +
  geom_point(size = 0.1, alpha = 0.05) +
  labs(x = "GranSim parameter value",
       y = "Spatial statistic value") +
  geom_text(data =
              df_cor_xy |>
              group_by(x_name, y_name, cor) |>
              summarize(x = max(x), y = max(y)),
            hjust = 1.1,
            parse = TRUE,
            size = 3,
            aes(label = sprintf("R==%+.2f", cor),
                x = Inf))
```

```{r session-info}
#| cache: false
sessionInfo()
```
