# Figure 6

```{r imports}
#| cache: false
#| message: false
library(dplyr)
library(readr)
library(stringr)
library(fs)
library(projpred)
library(snakecase)
library(rstanarm)
library(bayesplot)
library(ggplot2)
library(forcats)
library(tidyr)

source("R/config.R")
```

```{r prepare-inputs}
#| cache: true
#| cache.lazy: FALSE
file_stats <-
  file.path(dir_data,
            "2026-02-03-A-gr-20k-3rep",
            "output-lhs-7d-interval-stat-cols-10.csv.zst")
file_features <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            "02-cellprofiler-output-combined",
            "week22.csv.zst")
file_rank <-
  file.path(dir_data,
            "2026-02-17-A-cellprofiler-stats",
            "05-r-varsel-output",
            "rank_week22.csv")
## Prepare the df containing both the mtb output and predictors.
df_stats <-
  read_csv(zstdfile(file_stats),
           col_types = c(exp = "c", time = "i", TotMtbInGranScaledRing = "d"),
           col_select = c(exp, time, TotMtbInGranScaledRing)) %>%
  filter(time == max(time)) %>%
  select(-time)
ys <-
  df_stats %>%
  group_by(exp) %>%
  ## Experimentally, we do not see granulomas with more than 1M CFU.
  filter(! any(TotMtbInGranScaledRing > 1e6)) %>%
  mutate(rep =
           str_split_i(exp, fixed("."), 2L) %>%
           as.integer(),
         exp  =
           as.double(exp) %>%
           floor() %>%
           as.integer(),
         .after = 1L) %>%
  rename_with(to_snake_case) %>%
  dplyr::rename(Metadata_Site = exp,
                Metadata_Rep = rep)
## Predictive spatial features.
features <-
  read_csv(
    file_rank,
    col_select = c("size", "ranking_fulldata"),
    col_types = cols(
      size = "i",
      ranking_fulldata = "c")) |>
  filter(size != 0L) |>
  pull(ranking_fulldata)
## The CSV file has long lines; the default 2^17 buffer is insufficient.
Sys.setenv(VROOM_CONNECTION_SIZE = 2^19)
df <-
  inner_join(ys,
             read_csv(zstdfile(file_features),
                      ## We don't need the time column because we know it's the
                      ## last timepoint.
                      col_types = c(.default = "d",
                                    Metadata_Site = "i",
                                    Metadata_Rep = "i"),
                      col_select = all_of(c(
                        "Metadata_Site",
                        "Metadata_Rep",
                        features))),
             by = c("Metadata_Site", "Metadata_Rep")) %>%
  ungroup() %>%
  select(-starts_with("Metadata")) %>%
  dplyr::rename(mtb = tot_mtb_in_gran_scaled_ring) %>%
  mutate(mtb = log1p(mtb) / log(9)) %>%
  ## Cleanup inputs for regression.
  ##
  ## Replace problematic values with zero for now.
  mutate(across(everything(),
                function(x)
                  replace(x, is.na(x) | x < 0 | is.infinite(x), 0))) %>%
  ## Remove zero-values for now.
  filter(mtb > 0)
dim(df)

## Top log-CFU predictors from week 22.
formula_features <-
  str_c("mtb ~ ", str_c(features, collapse = "+")) |>
  as.formula()
formula_features
system.time({
  refm_fit <- stan_glm(
    formula = formula_features,
    family = gaussian(),
    data = df
  )
})

## The next few steps are from the package vignette: projpred:
## Projection predictive feature selection.
refm_obj <- get_refmodel(refm_fit)

system.time({
  cv_fits <- run_cvfun(refm_obj)
})

## Run CV in a single process; parallel processes use too much memory.
system.time({
  cvvs <- cv_varsel(
    refm_obj,
    cv_method = "kfold",
    cvfits = cv_fits,
    verbose = TRUE
  )
})

suggest_size(cvvs, stat = "mlpd")

rk <- ranking(cvvs)
## Marginals of the projected posterior.
( predictors_final <- head(rk[["fulldata"]],
                           suggest_size(cvvs, stat = "mlpd")) )
system.time({
  prj <- project(
    refm_obj,
    predictor_terms = predictors_final,
    ## Don't show the noisy progress bar.
    verbose = FALSE
  )
})
```

```{r figure-06-cfu-vs-smoothed-density}
#| cache: true
#| dependson: -1
#| fig.width: 6.5
#| fig.height: 3

## Predicted draws encompassing uncertainty from parameter estimation
## and sampling.
df_sub <-
  df |>
  ## Subset to reduce overplotting.
  mutate(ntile = ntile(mtb, 1000L), .before = 0L) |>
  group_by(ntile) |>
  slice_sample() |>
  ungroup()
prj_predict <- proj_predict(prj, df_sub)
ppc_dens_overlay(y = df_sub$mtb,
                 yrep = prj_predict) +
  labs(x = "CFU (counts)",
       y = "Smoothed density",
       color = "") +
  expand_limits(y = c(0, 0.3)) +
  ## Modified from scales::label_log() to use already log-scale
  ## exponents instead of converting.
  scale_x_continuous(labels = function(x) {
    exponent <- format(x, digits = 1)
    text <- paste0(10, "^", exponent)
    ret <- scales:::parse_safe(text)
    ret[is.na(x)] <- NA
    ret
  }) +
  scale_color_manual(labels = c("Simulated", "Regression predicted"),
                     values = palette.colors(2, palette = "Okabe-Ito")) +
  geom_rug(data = tibble(value = df_sub$mtb), alpha = 0.08) +
  theme(legend.position = "inside",
        legend.position.inside = c(.2, .9),
        text = element_text(family = "sans")) +
  ## Use default line width, otherwise the "Regression predicted" lines are too
  ## thin to see easily.
  guides(color = guide_legend(override.aes = list(linewidth = 1)))
```

```{r suppl-figure-corr-log-cfu}
#| cache: true
#| dependson: -1
#| fig.width: 6.5
#| fig.height: 9

df_r2 <-
  df_sub |>
  select(-ntile) |>
  pivot_longer(-mtb, names_to = "feature") |>
  group_by(feature) |>
  reframe(r2 = cor(mtb, value))
df_r2
levels <-
  tibble::deframe(df_r2) |>
  abs() |>
  sort() |>
  rev() |>
  names()
df_sub |>
  select(-ntile) |>
  pivot_longer(-mtb, names_to = "feature") |>
  mutate(mtb = expm1(mtb) * expm1(9),
         feature = fct(feature, levels)) |>
  ggplot(aes(value, mtb)) +
  theme_bw() +
  theme(strip.text = element_text(size = 5)) +
  labs(
    x = "Spatial feature value",
    y = "log10(CFU)") +
  facet_wrap(
    ~ feature,
    ncol = 3,
    scales = "free_x") +
  scale_y_log10(label = scales::label_log()) +
  geom_point(alpha = 0.1) +
  geom_text(
    data =
      df_r2 |>
      mutate(mtb = 10^5,
             value = 0,
             feature = fct(feature, levels)),
    hjust = 1.1,
    parse = TRUE,
    size = 3,
    aes(label = sprintf("R^2==%+.2f", r2),
        x = Inf))
```

```{r session-info}
#| cache: false
sessionInfo()
```
